name: Build Mac arm64

on: [pull_request, push]

jobs:
  build_win64:
    name: Build Mac arm64
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          brew install cmake git gettext zstd
      - run: mkdir -p ${{ github.workspace }}/deps/build
      - run: mkdir -p ${{ github.workspace }}/deps/build/BambuStudio_dep

      - name: build deps
        id: cache_deps
        uses: actions/cache@v3
        env:
          cache-name: ${{ runner.os }}-cache-bambustudio_deps_arm64
        with:
          path: ${{ github.workspace }}/deps/build/BambuStudio_dep
          key: build-${{ env.cache-name }}

      - if: ${{ steps.cache_deps.outputs.cache-hit != 'true' }}
        name: build deps
        working-directory: ${{ github.workspace }}
        continue-on-error: true
        run: ./build_release_macos.sh -d -a arm64

